### ISSUE TITLE
chrome: cannot make it working

### ISSUE THREAD

**Issue by userquin** [Foso/compose-snake-web#4]
On Firefox it works...

Console output on Chrome:

```shell
"ClassCastException
    at THROW_CCE (webpack-internal:///./kotlin/web-getting-started.js:15975:11)
    at renderComposable$composable (webpack-internal:///./kotlin/web-getting-started.js:49667:77)
    at main (webpack-internal:///./kotlin/web-getting-started.js:60520:5)
    at Object.eval (webpack-internal:///./kotlin/web-getting-started.js:63015:3)
    at eval (webpack-internal:///./kotlin/web-getting-started.js:5:35)
    at eval (webpack-internal:///./kotlin/web-getting-started.js:8:2)
    at Object../kotlin/web-getting-started.js (http://localhost:8080/web-getting-started.js:353:1)
    at __webpack_require__ (http://localhost:8080/web-getting-started.js:409:42)
    at http://localhost:8080/web-getting-started.js:473:11
    at http://localhost:8080/web-getting-started.js:477:12"
```

**Comment by userquin** [comment]
it seems something related with the root that is not an `HTMLElement` on some composable function:

![imagen](https://user-images.githubusercontent.com/6311119/120020897-a5368c00-bfea-11eb-9bdd-c25c078648a1.png)

**Comment by userquin** [comment]
on chrome, document.getElementById('root') is returning an `Element` not a `HTMLElement` and so `renderComposable(rootElementId = "root")` just fails

**Comment by userquin** [comment]
I file an issue on compose-js, see https://github.com/JetBrains/compose-jb/issues/714
